export const SET_TODOS = "SET_TODOS";
export const ADD_TODO = "ADD_TODO";
export const NEW_TODO_SET_CONTENT = "NEW_TODO_SET_CONTENT";
export const UPDATE_TODO = "UPDATE_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const MARK_ALL_TODOS_COMPLETE = "MARK_ALL_TODOS_COMPLETE";
export const MARK_ALL_TODOS_ACTIVE = "MARK_ALL_TODOS_ACTIVE";
export const SET_FILTER = "SET_FILTER";
