import * as actions from "../../state/actions";
import { generateCmdsFromActions, redux } from "effects-as-data-redux";
import { cmds } from "effects-as-data-universal/es5";
import { getLocal, setLocal } from "./store";

const autoGeneratedCmdsFromReduxActions = generateCmdsFromActions(actions);

// Combine the commands to access the redux state from effects-as-data-redux,
// the generated commands from the redux actions in this project and the
// effects-as-data-universal commands
export default {
  ...redux,
  ...autoGeneratedCmdsFromReduxActions,
  ...cmds,
  getLocal,
  setLocal
};
